// Package lambdalabs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package lambdalabs

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes  = "basicAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	GlobalaccountInactive                           ErrorCode = "global/account-inactive"
	GlobalinvalidApiKey                             ErrorCode = "global/invalid-api-key"
	GlobalinvalidParameters                         ErrorCode = "global/invalid-parameters"
	GlobalobjectDoesNotExist                        ErrorCode = "global/object-does-not-exist"
	GlobalquotaExceeded                             ErrorCode = "global/quota-exceeded"
	Globalunknown                                   ErrorCode = "global/unknown"
	InstanceOperationslaunchfileSystemInWrongRegion ErrorCode = "instance-operations/launch/file-system-in-wrong-region"
	InstanceOperationslaunchfileSystemsNotSupported ErrorCode = "instance-operations/launch/file-systems-not-supported"
	InstanceOperationslaunchinsufficientCapacity    ErrorCode = "instance-operations/launch/insufficient-capacity"
	SshKeyskeyInUse                                 ErrorCode = "ssh-keys/key-in-use"
)

// Defines values for InstanceStatus.
const (
	InstanceStatusActive      InstanceStatus = "active"
	InstanceStatusBooting     InstanceStatus = "booting"
	InstanceStatusTerminated  InstanceStatus = "terminated"
	InstanceStatusTerminating InstanceStatus = "terminating"
	InstanceStatusUnhealthy   InstanceStatus = "unhealthy"
)

// Defines values for UserStatus.
const (
	UserStatusActive      UserStatus = "active"
	UserStatusDeactivated UserStatus = "deactivated"
)

// Datetime A date and time, formatted as an ISO 8601 time stamp
type Datetime = string

// Error defines model for error.
type Error struct {
	// Code Unique identifier for the type of error
	Code ErrorCode `json:"code"`

	// Message Detailed description of the error
	Message string `json:"message"`

	// Suggestion Suggestion of possible ways to fix the error.
	Suggestion *string `json:"suggestion"`
}

// ErrorCode Unique identifier for the type of error
type ErrorCode string

// ErrorResponseBody defines model for errorResponseBody.
type ErrorResponseBody struct {
	Error Error `json:"error"`

	// FieldErrors Details about errors on a per-parameter basis
	FieldErrors *map[string]Error `json:"field_errors,omitempty"`
}

// FileSystem Information about a shared file system
type FileSystem struct {
	// BytesUsed Approximate amount of storage used by the file system, in bytes. This value is an estimate that is updated every several hours.
	BytesUsed *int `json:"bytes_used,omitempty"`

	// Created A date and time, formatted as an ISO 8601 time stamp
	Created Datetime `json:"created"`

	// CreatedBy Information about a user in your team
	CreatedBy User `json:"created_by"`

	// Id Unique identifier (ID) of a file system
	Id FileSystemId `json:"id"`

	// IsInUse Whether the file system is currently in use by an instance. File systems that are in use cannot be deleted.
	IsInUse bool `json:"is_in_use"`

	// MountPoint Absolute path indicating where on instances the file system will be mounted
	MountPoint string `json:"mount_point"`

	// Name Name of a file system
	Name   FileSystemName `json:"name"`
	Region Region         `json:"region"`
}

// FileSystemId Unique identifier (ID) of a file system
type FileSystemId = string

// FileSystemName Name of a file system
type FileSystemName = string

// Instance Virtual machine (VM) in Lambda Cloud
type Instance struct {
	// FileSystemNames Names of the file systems, if any, attached to the instance
	FileSystemNames []FileSystemName `json:"file_system_names"`

	// Hostname Hostname assigned to this instance, which resolves to the instance's IP.
	Hostname *string `json:"hostname"`

	// Id Unique identifier (ID) of an instance
	Id InstanceId `json:"id"`

	// InstanceType Hardware configuration and pricing of an instance type
	InstanceType *InstanceType `json:"instance_type,omitempty"`

	// Ip IPv4 address of the instance
	Ip *string `json:"ip"`

	// JupyterToken Secret token used to log into the jupyter lab server hosted on the instance.
	JupyterToken *string `json:"jupyter_token"`

	// JupyterUrl URL that opens a jupyter lab notebook on the instance.
	JupyterUrl *string `json:"jupyter_url"`

	// Name User-provided name for the instance
	Name   *InstanceName `json:"name"`
	Region *Region       `json:"region,omitempty"`

	// SshKeyNames Names of the SSH keys allowed to access the instance
	SshKeyNames []SshKeyName `json:"ssh_key_names"`

	// Status The current status of the instance
	Status InstanceStatus `json:"status"`
}

// InstanceStatus The current status of the instance
type InstanceStatus string

// InstanceId Unique identifier (ID) of an instance
type InstanceId = string

// InstanceName User-provided name for the instance
type InstanceName = string

// InstanceType Hardware configuration and pricing of an instance type
type InstanceType struct {
	// Description Long name of the instance type
	Description string `json:"description"`

	// Name Name of an instance type
	Name InstanceTypeName `json:"name"`

	// PriceCentsPerHour Price of the instance type, in US cents per hour
	PriceCentsPerHour int `json:"price_cents_per_hour"`
	Specs             struct {
		// MemoryGib Amount of RAM, in gibibytes (GiB)
		MemoryGib int `json:"memory_gib"`

		// StorageGib Amount of storage, in gibibytes (GiB).
		StorageGib int `json:"storage_gib"`

		// Vcpus Number of virtual CPUs
		Vcpus int `json:"vcpus"`
	} `json:"specs"`
}

// InstanceTypeName Name of an instance type
type InstanceTypeName = string

// Region defines model for region.
type Region struct {
	// Description Long name of a region
	Description string `json:"description"`

	// Name Short name of a region
	Name RegionName `json:"name"`
}

// RegionName Short name of a region
type RegionName = string

// SshKey Information about a stored SSH key, which can be used to access instances over SSH
type SshKey struct {
	// Id Unique identifier (ID) of an SSH key
	Id SshKeyId `json:"id"`

	// Name Name of the SSH key
	Name SshKeyName `json:"name"`

	// PrivateKey Private key for the SSH key. Only returned when generating a new key pair.
	PrivateKey *SshPrivateKey `json:"private_key"`

	// PublicKey Public key for the SSH key
	PublicKey SshPublicKey `json:"public_key"`
}

// SshKeyId Unique identifier (ID) of an SSH key
type SshKeyId = string

// SshKeyName Name of the SSH key
type SshKeyName = string

// SshPrivateKey Private key for the SSH key. Only returned when generating a new key pair.
type SshPrivateKey = string

// SshPublicKey Public key for the SSH key
type SshPublicKey = string

// User Information about a user in your team
type User struct {
	// Email Email address of the user
	Email string `json:"email"`

	// Id Unique identifier for the user
	Id string `json:"id"`

	// Status Status of the user's account
	Status UserStatus `json:"status"`
}

// UserStatus Status of the user's account
type UserStatus string

// AddSSHKeyOKResponse The added or generated SSH public key. If a new key pair was generated, the response body contains a `private_key` property that *must* be saved locally. Lambda Cloud does not store private keys.
type AddSSHKeyOKResponse struct {
	// Data Information about a stored SSH key, which can be used to access instances over SSH
	Data SshKey `json:"data"`
}

// BadRequest defines model for badRequest.
type BadRequest = ErrorResponseBody

// FileSystemsOKResponse defines model for fileSystems.
type FileSystemsOKResponse struct {
	Data []FileSystem `json:"data"`
}

// Forbidden defines model for forbidden.
type Forbidden = ErrorResponseBody

// InstanceOKResponse defines model for instance.
type InstanceOKResponse struct {
	// Data Virtual machine (VM) in Lambda Cloud
	Data Instance `json:"data"`
}

// InstanceTypes defines model for instanceTypes.
type InstanceTypes struct {
	// Data Dict of instance_type_name to instance_type and region availability.
	Data map[string]struct {
		// InstanceType Hardware configuration and pricing of an instance type
		InstanceType InstanceType `json:"instance_type"`

		// RegionsWithCapacityAvailable List of regions, if any, that have this instance type available
		RegionsWithCapacityAvailable []Region `json:"regions_with_capacity_available"`
	} `json:"data"`
}

// Instances defines model for instances.
type Instances struct {
	Data []Instance `json:"data"`
}

// InternalServerError defines model for internalServerError.
type InternalServerError = ErrorResponseBody

// LaunchOKResponse defines model for launch.
type LaunchOKResponse struct {
	Data struct {
		// InstanceIds The unique identifiers (IDs) of the launched instances. Note: if a quantity was specified, fewer than the requested quantity might have been launched.
		InstanceIds []InstanceId `json:"instance_ids"`
	} `json:"data"`
}

// NotFound defines model for notFound.
type NotFound = ErrorResponseBody

// RestartOKResponse defines model for restart.
type RestartOKResponse struct {
	Data struct {
		// RestartedInstances List of instances that were restarted. Note: this list might not contain all instances requested to be restarted.
		RestartedInstances []Instance `json:"restarted_instances"`
	} `json:"data"`
}

// SshKeys defines model for sshKeys.
type SshKeys struct {
	Data []SshKey `json:"data"`
}

// TerminateOKResponse defines model for terminate.
type TerminateOKResponse struct {
	Data struct {
		// TerminatedInstances List of instances that were terminated. Note: this list might not contain all instances requested to be terminated.
		TerminatedInstances []Instance `json:"terminated_instances"`
	} `json:"data"`
}

// Unauthorized defines model for unauthorized.
type Unauthorized = ErrorResponseBody

// AddSSHKey The name for the SSH key. Optionally, an existing public key can be supplied for the `public_key` property. If the `public_key` property is omitted, a new key pair is generated. The private key is returned in the response.
type AddSSHKey struct {
	// Name Name of the SSH key
	Name SshKeyName `json:"name"`

	// PublicKey Public key for the SSH key
	PublicKey *SshPublicKey `json:"public_key,omitempty"`
}

// Launch defines model for launch.
type Launch struct {
	// FileSystemNames Names of the file systems to attach to the instances. Currently, only one (if any) file system may be specified.
	FileSystemNames *[]FileSystemName `json:"file_system_names,omitempty"`

	// InstanceTypeName Name of an instance type
	InstanceTypeName InstanceTypeName `json:"instance_type_name"`

	// Name User-provided name for the instance
	Name *InstanceName `json:"name"`

	// Quantity Number of instances to launch
	Quantity *int `json:"quantity,omitempty"`

	// RegionName Short name of a region
	RegionName RegionName `json:"region_name"`

	// SshKeyNames Names of the SSH keys to allow access to the instances. Currently, exactly one SSH key must be specified.
	SshKeyNames []SshKeyName `json:"ssh_key_names"`
}

// Restart defines model for restart.
type Restart struct {
	// InstanceIds The unique identifiers (IDs) of the instances to restart
	InstanceIds []InstanceId `json:"instance_ids"`
}

// Terminate defines model for terminate.
type Terminate struct {
	// InstanceIds The unique identifiers (IDs) of the instances to terminate
	InstanceIds []InstanceId `json:"instance_ids"`
}

// LaunchInstanceJSONBody defines parameters for LaunchInstance.
type LaunchInstanceJSONBody struct {
	// FileSystemNames Names of the file systems to attach to the instances. Currently, only one (if any) file system may be specified.
	FileSystemNames *[]FileSystemName `json:"file_system_names,omitempty"`

	// InstanceTypeName Name of an instance type
	InstanceTypeName InstanceTypeName `json:"instance_type_name"`

	// Name User-provided name for the instance
	Name *InstanceName `json:"name"`

	// Quantity Number of instances to launch
	Quantity *int `json:"quantity,omitempty"`

	// RegionName Short name of a region
	RegionName RegionName `json:"region_name"`

	// SshKeyNames Names of the SSH keys to allow access to the instances. Currently, exactly one SSH key must be specified.
	SshKeyNames []SshKeyName `json:"ssh_key_names"`
}

// RestartInstanceJSONBody defines parameters for RestartInstance.
type RestartInstanceJSONBody struct {
	// InstanceIds The unique identifiers (IDs) of the instances to restart
	InstanceIds []InstanceId `json:"instance_ids"`
}

// TerminateInstanceJSONBody defines parameters for TerminateInstance.
type TerminateInstanceJSONBody struct {
	// InstanceIds The unique identifiers (IDs) of the instances to terminate
	InstanceIds []InstanceId `json:"instance_ids"`
}

// AddSSHKeyJSONBody defines parameters for AddSSHKey.
type AddSSHKeyJSONBody struct {
	// Name Name of the SSH key
	Name SshKeyName `json:"name"`

	// PublicKey Public key for the SSH key
	PublicKey *SshPublicKey `json:"public_key,omitempty"`
}

// LaunchInstanceJSONRequestBody defines body for LaunchInstance for application/json ContentType.
type LaunchInstanceJSONRequestBody LaunchInstanceJSONBody

// RestartInstanceJSONRequestBody defines body for RestartInstance for application/json ContentType.
type RestartInstanceJSONRequestBody RestartInstanceJSONBody

// TerminateInstanceJSONRequestBody defines body for TerminateInstance for application/json ContentType.
type TerminateInstanceJSONRequestBody TerminateInstanceJSONBody

// AddSSHKeyJSONRequestBody defines body for AddSSHKey for application/json ContentType.
type AddSSHKeyJSONRequestBody AddSSHKeyJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListFileSystems request
	ListFileSystems(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LaunchInstanceWithBody request with any body
	LaunchInstanceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	LaunchInstance(ctx context.Context, body LaunchInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RestartInstanceWithBody request with any body
	RestartInstanceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RestartInstance(ctx context.Context, body RestartInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TerminateInstanceWithBody request with any body
	TerminateInstanceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	TerminateInstance(ctx context.Context, body TerminateInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InstanceTypes request
	InstanceTypes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListInstances request
	ListInstances(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetInstance request
	GetInstance(ctx context.Context, id InstanceId, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListSSHKeys request
	ListSSHKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddSSHKeyWithBody request with any body
	AddSSHKeyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddSSHKey(ctx context.Context, body AddSSHKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteSSHKey request
	DeleteSSHKey(ctx context.Context, id SshKeyId, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListFileSystems(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListFileSystemsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LaunchInstanceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLaunchInstanceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LaunchInstance(ctx context.Context, body LaunchInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLaunchInstanceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RestartInstanceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRestartInstanceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RestartInstance(ctx context.Context, body RestartInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRestartInstanceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TerminateInstanceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTerminateInstanceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) TerminateInstance(ctx context.Context, body TerminateInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTerminateInstanceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InstanceTypes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInstanceTypesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListInstances(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListInstancesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetInstance(ctx context.Context, id InstanceId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetInstanceRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListSSHKeys(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListSSHKeysRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddSSHKeyWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddSSHKeyRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddSSHKey(ctx context.Context, body AddSSHKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddSSHKeyRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteSSHKey(ctx context.Context, id SshKeyId, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteSSHKeyRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListFileSystemsRequest generates requests for ListFileSystems
func NewListFileSystemsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/file-systems")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLaunchInstanceRequest calls the generic LaunchInstance builder with application/json body
func NewLaunchInstanceRequest(server string, body LaunchInstanceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewLaunchInstanceRequestWithBody(server, "application/json", bodyReader)
}

// NewLaunchInstanceRequestWithBody generates requests for LaunchInstance with any type of body
func NewLaunchInstanceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/instance-operations/launch")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRestartInstanceRequest calls the generic RestartInstance builder with application/json body
func NewRestartInstanceRequest(server string, body RestartInstanceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRestartInstanceRequestWithBody(server, "application/json", bodyReader)
}

// NewRestartInstanceRequestWithBody generates requests for RestartInstance with any type of body
func NewRestartInstanceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/instance-operations/restart")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTerminateInstanceRequest calls the generic TerminateInstance builder with application/json body
func NewTerminateInstanceRequest(server string, body TerminateInstanceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTerminateInstanceRequestWithBody(server, "application/json", bodyReader)
}

// NewTerminateInstanceRequestWithBody generates requests for TerminateInstance with any type of body
func NewTerminateInstanceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/instance-operations/terminate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewInstanceTypesRequest generates requests for InstanceTypes
func NewInstanceTypesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/instance-types")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListInstancesRequest generates requests for ListInstances
func NewListInstancesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/instances")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetInstanceRequest generates requests for GetInstance
func NewGetInstanceRequest(server string, id InstanceId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/instances/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListSSHKeysRequest generates requests for ListSSHKeys
func NewListSSHKeysRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ssh-keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddSSHKeyRequest calls the generic AddSSHKey builder with application/json body
func NewAddSSHKeyRequest(server string, body AddSSHKeyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddSSHKeyRequestWithBody(server, "application/json", bodyReader)
}

// NewAddSSHKeyRequestWithBody generates requests for AddSSHKey with any type of body
func NewAddSSHKeyRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ssh-keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteSSHKeyRequest generates requests for DeleteSSHKey
func NewDeleteSSHKeyRequest(server string, id SshKeyId) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ssh-keys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListFileSystemsWithResponse request
	ListFileSystemsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListFileSystemsResponse, error)

	// LaunchInstanceWithBodyWithResponse request with any body
	LaunchInstanceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LaunchInstanceResponse, error)

	LaunchInstanceWithResponse(ctx context.Context, body LaunchInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*LaunchInstanceResponse, error)

	// RestartInstanceWithBodyWithResponse request with any body
	RestartInstanceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RestartInstanceResponse, error)

	RestartInstanceWithResponse(ctx context.Context, body RestartInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*RestartInstanceResponse, error)

	// TerminateInstanceWithBodyWithResponse request with any body
	TerminateInstanceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TerminateInstanceResponse, error)

	TerminateInstanceWithResponse(ctx context.Context, body TerminateInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*TerminateInstanceResponse, error)

	// InstanceTypesWithResponse request
	InstanceTypesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*InstanceTypesResponse, error)

	// ListInstancesWithResponse request
	ListInstancesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListInstancesResponse, error)

	// GetInstanceWithResponse request
	GetInstanceWithResponse(ctx context.Context, id InstanceId, reqEditors ...RequestEditorFn) (*GetInstanceResponse, error)

	// ListSSHKeysWithResponse request
	ListSSHKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSSHKeysResponse, error)

	// AddSSHKeyWithBodyWithResponse request with any body
	AddSSHKeyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddSSHKeyResponse, error)

	AddSSHKeyWithResponse(ctx context.Context, body AddSSHKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*AddSSHKeyResponse, error)

	// DeleteSSHKeyWithResponse request
	DeleteSSHKeyWithResponse(ctx context.Context, id SshKeyId, reqEditors ...RequestEditorFn) (*DeleteSSHKeyResponse, error)
}

type ListFileSystemsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FileSystemsOKResponse
	JSON401      *Unauthorized
	JSON403      *Forbidden
}

// Status returns HTTPResponse.Status
func (r ListFileSystemsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListFileSystemsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LaunchInstanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LaunchOKResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r LaunchInstanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LaunchInstanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RestartInstanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RestartOKResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r RestartInstanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RestartInstanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type TerminateInstanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TerminateOKResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
	JSON500      *InternalServerError
}

// Status returns HTTPResponse.Status
func (r TerminateInstanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TerminateInstanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type InstanceTypesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *InstanceTypes
	JSON401      *Unauthorized
	JSON403      *Forbidden
}

// Status returns HTTPResponse.Status
func (r InstanceTypesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InstanceTypesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListInstancesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Instances
	JSON401      *Unauthorized
	JSON403      *Forbidden
}

// Status returns HTTPResponse.Status
func (r ListInstancesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListInstancesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetInstanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *InstanceOKResponse
	JSON401      *Unauthorized
	JSON403      *Forbidden
	JSON404      *NotFound
}

// Status returns HTTPResponse.Status
func (r GetInstanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetInstanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListSSHKeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SshKeys
	JSON401      *Unauthorized
	JSON403      *Forbidden
}

// Status returns HTTPResponse.Status
func (r ListSSHKeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListSSHKeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddSSHKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AddSSHKeyOKResponse
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
}

// Status returns HTTPResponse.Status
func (r AddSSHKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddSSHKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteSSHKeyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequest
	JSON401      *Unauthorized
	JSON403      *Forbidden
}

// Status returns HTTPResponse.Status
func (r DeleteSSHKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteSSHKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListFileSystemsWithResponse request returning *ListFileSystemsResponse
func (c *ClientWithResponses) ListFileSystemsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListFileSystemsResponse, error) {
	rsp, err := c.ListFileSystems(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListFileSystemsResponse(rsp)
}

// LaunchInstanceWithBodyWithResponse request with arbitrary body returning *LaunchInstanceResponse
func (c *ClientWithResponses) LaunchInstanceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*LaunchInstanceResponse, error) {
	rsp, err := c.LaunchInstanceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLaunchInstanceResponse(rsp)
}

func (c *ClientWithResponses) LaunchInstanceWithResponse(ctx context.Context, body LaunchInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*LaunchInstanceResponse, error) {
	rsp, err := c.LaunchInstance(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLaunchInstanceResponse(rsp)
}

// RestartInstanceWithBodyWithResponse request with arbitrary body returning *RestartInstanceResponse
func (c *ClientWithResponses) RestartInstanceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RestartInstanceResponse, error) {
	rsp, err := c.RestartInstanceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRestartInstanceResponse(rsp)
}

func (c *ClientWithResponses) RestartInstanceWithResponse(ctx context.Context, body RestartInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*RestartInstanceResponse, error) {
	rsp, err := c.RestartInstance(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRestartInstanceResponse(rsp)
}

// TerminateInstanceWithBodyWithResponse request with arbitrary body returning *TerminateInstanceResponse
func (c *ClientWithResponses) TerminateInstanceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TerminateInstanceResponse, error) {
	rsp, err := c.TerminateInstanceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTerminateInstanceResponse(rsp)
}

func (c *ClientWithResponses) TerminateInstanceWithResponse(ctx context.Context, body TerminateInstanceJSONRequestBody, reqEditors ...RequestEditorFn) (*TerminateInstanceResponse, error) {
	rsp, err := c.TerminateInstance(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTerminateInstanceResponse(rsp)
}

// InstanceTypesWithResponse request returning *InstanceTypesResponse
func (c *ClientWithResponses) InstanceTypesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*InstanceTypesResponse, error) {
	rsp, err := c.InstanceTypes(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInstanceTypesResponse(rsp)
}

// ListInstancesWithResponse request returning *ListInstancesResponse
func (c *ClientWithResponses) ListInstancesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListInstancesResponse, error) {
	rsp, err := c.ListInstances(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListInstancesResponse(rsp)
}

// GetInstanceWithResponse request returning *GetInstanceResponse
func (c *ClientWithResponses) GetInstanceWithResponse(ctx context.Context, id InstanceId, reqEditors ...RequestEditorFn) (*GetInstanceResponse, error) {
	rsp, err := c.GetInstance(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetInstanceResponse(rsp)
}

// ListSSHKeysWithResponse request returning *ListSSHKeysResponse
func (c *ClientWithResponses) ListSSHKeysWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListSSHKeysResponse, error) {
	rsp, err := c.ListSSHKeys(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListSSHKeysResponse(rsp)
}

// AddSSHKeyWithBodyWithResponse request with arbitrary body returning *AddSSHKeyResponse
func (c *ClientWithResponses) AddSSHKeyWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddSSHKeyResponse, error) {
	rsp, err := c.AddSSHKeyWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddSSHKeyResponse(rsp)
}

func (c *ClientWithResponses) AddSSHKeyWithResponse(ctx context.Context, body AddSSHKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*AddSSHKeyResponse, error) {
	rsp, err := c.AddSSHKey(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddSSHKeyResponse(rsp)
}

// DeleteSSHKeyWithResponse request returning *DeleteSSHKeyResponse
func (c *ClientWithResponses) DeleteSSHKeyWithResponse(ctx context.Context, id SshKeyId, reqEditors ...RequestEditorFn) (*DeleteSSHKeyResponse, error) {
	rsp, err := c.DeleteSSHKey(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteSSHKeyResponse(rsp)
}

// ParseListFileSystemsResponse parses an HTTP response from a ListFileSystemsWithResponse call
func ParseListFileSystemsResponse(rsp *http.Response) (*ListFileSystemsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListFileSystemsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FileSystemsOKResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseLaunchInstanceResponse parses an HTTP response from a LaunchInstanceWithResponse call
func ParseLaunchInstanceResponse(rsp *http.Response) (*LaunchInstanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LaunchInstanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LaunchOKResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRestartInstanceResponse parses an HTTP response from a RestartInstanceWithResponse call
func ParseRestartInstanceResponse(rsp *http.Response) (*RestartInstanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RestartInstanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RestartOKResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseTerminateInstanceResponse parses an HTTP response from a TerminateInstanceWithResponse call
func ParseTerminateInstanceResponse(rsp *http.Response) (*TerminateInstanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TerminateInstanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TerminateOKResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseInstanceTypesResponse parses an HTTP response from a InstanceTypesWithResponse call
func ParseInstanceTypesResponse(rsp *http.Response) (*InstanceTypesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InstanceTypesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InstanceTypes
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseListInstancesResponse parses an HTTP response from a ListInstancesWithResponse call
func ParseListInstancesResponse(rsp *http.Response) (*ListInstancesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListInstancesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Instances
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseGetInstanceResponse parses an HTTP response from a GetInstanceWithResponse call
func ParseGetInstanceResponse(rsp *http.Response) (*GetInstanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetInstanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InstanceOKResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListSSHKeysResponse parses an HTTP response from a ListSSHKeysWithResponse call
func ParseListSSHKeysResponse(rsp *http.Response) (*ListSSHKeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListSSHKeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SshKeys
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseAddSSHKeyResponse parses an HTTP response from a AddSSHKeyWithResponse call
func ParseAddSSHKeyResponse(rsp *http.Response) (*AddSSHKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddSSHKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AddSSHKeyOKResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseDeleteSSHKeyResponse parses an HTTP response from a DeleteSSHKeyWithResponse call
func ParseDeleteSSHKeyResponse(rsp *http.Response) (*DeleteSSHKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteSSHKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List file systems
	// (GET /file-systems)
	ListFileSystems(c *gin.Context)
	// Launch instances
	// (POST /instance-operations/launch)
	LaunchInstance(c *gin.Context)
	// Restart instances
	// (POST /instance-operations/restart)
	RestartInstance(c *gin.Context)
	// Terminate an instance
	// (POST /instance-operations/terminate)
	TerminateInstance(c *gin.Context)
	// Retrieve list of offered instance types
	// (GET /instance-types)
	InstanceTypes(c *gin.Context)
	// List running instances
	// (GET /instances)
	ListInstances(c *gin.Context)
	// List details of a specific instance
	// (GET /instances/{id})
	GetInstance(c *gin.Context, id InstanceId)
	// List SSH keys
	// (GET /ssh-keys)
	ListSSHKeys(c *gin.Context)
	// Add SSH key
	// (POST /ssh-keys)
	AddSSHKey(c *gin.Context)
	// Delete SSH key
	// (DELETE /ssh-keys/{id})
	DeleteSSHKey(c *gin.Context, id SshKeyId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListFileSystems operation middleware
func (siw *ServerInterfaceWrapper) ListFileSystems(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListFileSystems(c)
}

// LaunchInstance operation middleware
func (siw *ServerInterfaceWrapper) LaunchInstance(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LaunchInstance(c)
}

// RestartInstance operation middleware
func (siw *ServerInterfaceWrapper) RestartInstance(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RestartInstance(c)
}

// TerminateInstance operation middleware
func (siw *ServerInterfaceWrapper) TerminateInstance(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.TerminateInstance(c)
}

// InstanceTypes operation middleware
func (siw *ServerInterfaceWrapper) InstanceTypes(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.InstanceTypes(c)
}

// ListInstances operation middleware
func (siw *ServerInterfaceWrapper) ListInstances(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListInstances(c)
}

// GetInstance operation middleware
func (siw *ServerInterfaceWrapper) GetInstance(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id InstanceId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInstance(c, id)
}

// ListSSHKeys operation middleware
func (siw *ServerInterfaceWrapper) ListSSHKeys(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSSHKeys(c)
}

// AddSSHKey operation middleware
func (siw *ServerInterfaceWrapper) AddSSHKey(c *gin.Context) {

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddSSHKey(c)
}

// DeleteSSHKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteSSHKey(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id SshKeyId

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteSSHKey(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/file-systems", wrapper.ListFileSystems)
	router.POST(options.BaseURL+"/instance-operations/launch", wrapper.LaunchInstance)
	router.POST(options.BaseURL+"/instance-operations/restart", wrapper.RestartInstance)
	router.POST(options.BaseURL+"/instance-operations/terminate", wrapper.TerminateInstance)
	router.GET(options.BaseURL+"/instance-types", wrapper.InstanceTypes)
	router.GET(options.BaseURL+"/instances", wrapper.ListInstances)
	router.GET(options.BaseURL+"/instances/:id", wrapper.GetInstance)
	router.GET(options.BaseURL+"/ssh-keys", wrapper.ListSSHKeys)
	router.POST(options.BaseURL+"/ssh-keys", wrapper.AddSSHKey)
	router.DELETE(options.BaseURL+"/ssh-keys/:id", wrapper.DeleteSSHKey)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcC2/bOLb+K4TuAu3sSn7FSR0Di3udNm2N9JE26XQ7k8KhpWOLU4lUSSqJp+v/fsGH",
	"nlZsx006XWAHAzSW+Dg8/Hje1DfHZ3HCKFApnOE3h8PXFIQ8YgEB/QAHwdnZyxNYqB8+oxKo1M+TJCI+",
	"loTR9h+CUfVM+CHE2PYi6hWOTjlLgEs92gxHAlwnAOFzkqj3ztA5DwFRHAOaMY5kCOjs7CX6AosWepuY",
	"IaKFizBFcEOEJHSOknQaEV+1QT6maApIpIoaCPIxLk2byRdYXKLEkLBoofHs9reICMRiIiUELsKIwrWe",
	"IcGEq1dzoMCxhKCFFMUJJ1dYgm5CBOIgU04hQITqGTiIhFEBLcd14AbHSQSKLWqdztChcB0tvHxE7wss",
	"nKXrJCVWZW2/OX/jMHOGzv+0i41qG0aLthDhCSzeqJaqf76qLfqd6sZqX5dLV2874RA4w9/NxJ9dRy4S",
	"RSyb/gG+dJbVZpKnsHSdCKfUD+8PGlUWzEgEE7EQEuKJoko/rKJHrV0gZvZVtUemvUCSISwl9kP1l3pL",
	"qJCY+iBa6GnKOVCpgMVotECMAnpMZgjTxS/lUVCMFxpfCfhkRiBQ+0nU8Js4rAY502NkuxPjm7Hp2c15",
	"iznHeusz2ibqxWSbrc96nC8SyKa4S7+sz9cUU0nkwrB2htNIagprbE7jKXDF55yLiq12+/XiSJzGumdM",
	"aP63XSehEubAHQ2hOWF0qyWaphmhQoQK2lsBwYoQA4IoYtcI+z4IsR4KcIN9adFgR0BxKuRuCKiezcru",
	"x4TeBoXaWSxzqxEldb5seW45CIm5fKiDmxNKgoatUvIzpeRrCogEQKXiKxfo8fiZ+CXbwQrMMmq35HzW",
	"dxwozq/lb4XQLXkngceEYgn/Idwr6P0Z+GfAp5Xjj7MvcBBAgBgvtLg+4IUhoU2DmtK/xiWt71bUOpqy",
	"YIEUtZhQgTC6tPZAzaSQIZbo70qG/F0LEXwFAYqYr2yaFnqF42mA0dOIpQEKGAhEmURCMl6xL0TNiAiw",
	"1DwggTN0Ooe9zv6g5z+ZzTr97t7hIez1B7093JnCQW+/P3DcdUaHQl5OtzN0PPXf0fGL8Rv0/myETt+P",
	"fx2dH6OT40/6zQU9Of6Enr59c3785lw/OX7z7JaWTtUeUWLK4wKj0Wg0Otp78yd+2l34vWP189no3ehI",
	"PR69ezY7SfBVf/zq035/TH+D3pMXKBVKc6zYRxkbNsvgFdTqrs1orWLn7YnjOjfenHmWiaMMrW9P3lss",
	"qDMyxcF7YzjfCcXrSAfOGc/mOGLBook+OylKMMcxSCUHroGr83+FIxK0FG2FJSIeSmDliLybZbRRuuy+",
	"T8+LRVd3asb4lAQB0B+7Uc+zaVtla++h92MbIX+PTB/bIascLxuqD47A5i67aV/DgO2t8MK6FZNrIsOJ",
	"jxPsE7mY4CtMIjy14rvCxFdESKW1bUcXGS/ENaojxFeAZEhErtGRogoVA26p0s3w26tz3WrzclZhUgfJ",
	"M+LLsttQmK7KNKk8RZgGlg/ZAklE5KKm/uZJOuneTHC302ncrur83Rv0/vxfaNTtdNDjXh+9OPqlUInl",
	"obQq9GHiK75NEuCTkKXcGToD9U6Z/5rJMcSMLyZzMnWGg07HdZS6xnMwT/a7Pde58pNUOMNef7kNIH6v",
	"UzxKhSTURedwg0VBayo8eeN1neXnpasJ799M8EFnKyb0DRNU62Ym5GPdyoVu9wez4TRkQMmNi0ac/Mko",
	"rnAC/2k4sVwVU7sLs5Ks+jk0ZSGi71FP6lVK4BRHZ8CvgB8r/fVjteEZi0GGhM5RSuEmAV8Z5Mz3lStu",
	"jJaHjSut1xYP5JOZJekQYR58eMMkDLXIR1kcRrsdebTBRTO4Bq60QRZY1BYfBEWHmMxDqyqmADSfqPUX",
	"+Hv3ZUq80muoGhKUyecspcGPxepbTXThnukodMt5+BjKDiC1FEEwqQiyZoujFCNQpob2G/IBMmhq2yNS",
	"PQzKFAes24twFJUGKYApmfJ1i6HuCsONIGxa5gNi8b2ZrgpG41n+HHoi83LvV0s8eJhrB4DnNO2M8GKE",
	"74d4aax7x3jjSh8Q5OfZfFWYpxSnMmSc/Ak/WO5+KM3c0gu13S10QJK4wdQdIfVOuxKqgYtmjMdYqk3D",
	"AmGKxmdv0eCg09WvkZA4Tsr+hdPr9Pa8Ts/r9c97nWF/MNw/+EenM9S2sWWrkJzQuWIPZLbTHTDsswC2",
	"4tBT1XDpOjEIgecNa30GEpMIAlR6nFkbhrLywkan4yxbacNDLoKbREHHRYyjACKwUF5Zp0jncxBm2joV",
	"Z/k7NXfChCDTCNA1NumXGbkpCKq4cs5TDnqvdNg1I0/vHF8gPMeEqvY0jayPIHkKK8TVToDmbsGzJge1",
	"YO7KWj7Ubbg8oawdVDYr+ErTWM03j9gUR+2UfqHsmjpu9sCy2MMJsZFW+wL7Pkup9AjFviRXsNqlCOYV",
	"7wz1nrJCPMqkp62Q4vXXlEnswY0PEEBQyhR5Cnn6jIq2sQuVCEpnM+IToNLLXLH1XWYkAs9kRD1CvWvO",
	"6NyzIYVtOxq6RZokTKluk7hSrBHtL7BQw6aivF+1Q1YRF3c7cPkh3XjiTLgUomCif4p1EaWtBms6rwLh",
	"KUulQZJAjCKMEuDFtqMpFkQ4m2S9maQJ4KUI691SJWNqpKWOwGgiMRIh5hCUk+JOncHThQQxSYVRETV5",
	"nCSc3ZBYH/RYIV+dIhstQKoPmi7qyXsXEYr0qC10rtTzFY7UsdQCXMkaPZxW6kSgNAl0RgeugC+QUP/g",
	"CIUs5dXMSa/bf9If7B30B015aV8Lo2DT1uaap+gymW6stzApDFenbLaNjhtvjIgJoYq3q6z9GIIMgdeZ",
	"p1jiZ0ltxchUgOIxprkp00LPK5USipFYpw10Yx9TZQRNoUEnTBmLAOtIot7NScKIsQdq+z4VLEoloATL",
	"EBEaaFOBztF1qMwwRivWWXUB1ySK1Ox6Ai0qCp3RDlkM7XSaUpm2DTa9mWjSWdtUGKxWaViptmU4te4d",
	"B1mUqsBTBSZVpuWzlbd5/YEeB9sorcfjZzrsgGvHtmDjhrThkyaG1pjVWIGxfta1+1VOilQH/pVwmeII",
	"xdgPCQX0+NfXvyislvOnzn3WDhVReFNBZCz+cmJ99zKgeuVPyISkjfx8ad8gLASZ04yIUjLARdch8UPl",
	"a7PoClbKWx4JND6t2lzdjtfxBl738KDlK761Is3ECE9Fy2fxZntrGyFWDSh9V0KFJKuMGZ9e9REOAg5C",
	"1Cseaott2f+3WdcfabKQwCeSfYEmOxd8DhLpt0ZxSYYiNkeEWrbbAVCEp0jo2CpSuwuBEndlIqtbsr93",
	"eDCYdXsDv4/7/cHh9GAw8Ht+B3cH3aAz2LsL7SmPGgTE+1dGxrMEdLVCmVDKJEwZ+7KexlDKRAzbbdvT",
	"28N+39/3D7zDTu/A6z8Jet4h3tvznnRh5vtTP+gAWGiJBPugwdX+X828f97HgncpdbubbN+x4kyXmxlw",
	"ZDVnO8iNavFYXWYIiWV6Sxjaqn5k2jQdD+u55O7HlDGlmR3l7YeAIxkqRZUFIMybIhzRYKI3aUFLYp2J",
	"boNcbtJ4JQlyF31Hm+XABm13uE4dNeu6D0JZ7JxdkQCCavlyIwWSY0IJnXuUBeB1TcXkK6BzGTrDg74u",
	"Ccx+dreRwWUxeTcj/yXmwbWy9nxGZ2Secmvv0wAlnPjKRquyEtlkcC16Vx50JQLH6NxwpYa/bKySjG5M",
	"0H7XeS+XxDanM1eSjapVI63aFflwhvQIyk/TjkV5Bd1up8mfyFOld/BUy1nVFYM6d57ej15rquZkSrST",
	"hB6/IJprOU06JdtAUzlJe/sEtlnTJBWtoNO8q7PYxO+3W0uIr6w99/T0g6g4aP3V4WqyxYztljlVXdbG",
	"EKk1z8u03YKSbA/Xyaccardbw3QN+KsFCCugLxTWXcLqWx9MjHL/oxQmrJUf7HQSy5Xbm/nfxODSCKuW",
	"WMi4XL+KrFqiKZZpsiX3EBmRjNtC0i+wyGxxeyMlMxCtDVA4u0yZhWdnL1cE6maz2lBujOodboeUKz03",
	"Xw8xrW1e6Z5ulpT949KQTfufr/Vu6t9uxl20/+B2kKw/2SWzrzJfjH1lUCvzYFXPN81U4nWTZsrvGa1e",
	"kKLRorh6dB0CzQqWlRavljNX7fmNhb6vx+Pj5N34aDQ6eTp6dzzaH79YTK8G7evg3euDT/3Fp/MX5Bji",
	"/rnwj34jo4//OLxZfOwlz+Tg7Mmvz2R8QVut1gWFpx/7h3uDj4fp4M3e+/aX5MU16crfPpEXr18dfeif",
	"iM7Xk+ek/Ssc4+PDt6/gdP/ju8Hpl39e0M3lxRuNpAoWVzlb3CKrMbYas/i+uuUKAPqdw4MGOnXD75dH",
	"ahilshcs5UgCXg3UQoxJg394rB7XHWpLfcmEBRzHWML/2Uc2XHBLeGDbvMrKNLvY6rf5Q2cVH0hN9Ugg",
	"m4Bp8oQC0H/ewc0xHM0paLQ+BPgpJ3JxpkSkjZhjQfxRKsNVmo/UK/Ty/PwU4VSGimEmydpCI+tahoAD",
	"4MLz0OXI5kh1iyEynS/STmfPn2IBB30E1GdBZtQnRAlc/R6Gl+jfaweotL50bAJWB4FVq2IjQikTXQUP",
	"mAPPlmV+PdcwVc5rKkPPjlBH85FuuvOiTe+NROtmdaqX2pibsQZ7+HSsUaqr5RQu6BxdExlqLNnQ44vT",
	"D3n4URIZmdKl0q2O0enYcZ0r4MKWo7b2W13FK5YAxQlxhs5eq9PShZdYhhoclayZrniFhgD7e5CcgC4P",
	"BlO+wGaVIKajJzHendKjuiyiVBfv1C7i9EwpaZNyz9u1y5cJlq7T73Q396nUEOhOe1tMlNfp6yOUxjHm",
	"i6y2o7JM9b59ew5STZUw0cBBU2OmTDIKiHEUM16+OaVNyzm5gpoB31plrB5oXPj9xSXqxe0rLd2zzkhd",
	"7rIlRd/+Ns1LV1V+1AaqHv3NPfL6vqXr7G+zlKY61hpaNG+KTb0dLKVivma02CowE86rwkKsQsK2/h5M",
	"ZBTtBIpS5/+ioo4KuznbwKJSBNcMjLxySqzIi1Vc5I2/BxkFUTtho9L9v+iooyPfoko4uYoQmd1luk01",
	"p1wnWoKsQitT0CvxRaVnZsBNGUTdqjCfmghs2QihfpQGYMvAa9eFCLXxB8AlgWfKlioFAfmdi5Z2oqrw",
	"HFfuau0Cruptr7/ERMgto4zpGYerjK9u6WZDq3E/eUqpMgzXqAJlsYzzWb6Hp3+lybWyUF0/6kfEwxHB",
	"ejW/O5FwPle52v5GguUWrM0wro0ue/vBL+W5DfZt/YiuemFcV+pWDhQRGZ1N4H4BZX1cqrJbvXzUeJ8j",
	"jzPVE3qqh7LeiytK2jesXnx3tyyOLefOl5+/By4/r6xehdf6/TdHNasXvJtLlCVmG8+lucu926nMbgD8",
	"dWcyX9rSvcU2GQVBKSp6QS/oOdMlXuXPKWURQheBUo6ae8lqcKz5o0n2OFgDRX8XoWXnyT41UAtEuvor",
	"S2uGnHEWrw6KzrDd2eq3Fkqt7bcZBIvBVJnpyAu00HPGkY0wucaH91MeDRWdl5eXF1T9QlmJQ1NZTBsn",
	"pH3VzSGILi4uKEKeN8Mkyn6k6G/fXo1eHz0bTUan48nJ8aflMHv3L3T69uw8+xWgR98utKy4cIbowrHs",
	"uXCWj2yTf6M/viKPo0etAEvcKq34kQl06IhwK4FYLcIPYxagfqdTPNTruqDnIVAX4Zna1wVL7d2wSlJK",
	"8+PSknBZqXgicmhHEiJEHsmGt7GWfIjxqaHJNl45avlXE3axdosPhOxk7Va6/6zWbuVsq0ObRaIrgi9X",
	"pqYss+lCgHpeOvGr1ohpku/Gd2rBImB+v0qwyHTdpgIbFk4YRSLV+bZZGv3HbLfdtGLHSyFjvSmlYPHv",
	"n5fut0qc9ffPikOm2qxpD085C1Lf8EY3clxHF4k528g7R01nmhePPi//PwAA//8pVpsSNVAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
